---
-   name: Install and configure Docker
    become: true
    block:
        -   name: Install dependencies
            ansible.builtin.apt:
                name:
                    - apt-transport-https
                    - ca-certificates
                    - curl
                    - software-properties-common
                state: present
                update_cache: yes

        -   name: Add Docker GPG key
            ansible.builtin.apt_key:
                url: https://download.docker.com/linux/debian/gpg
                state: present

        -   name: Add Docker APT repository
            ansible.builtin.apt_repository:
                repo: deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
                state: present
                filename: docker
                update_cache: yes

        -   name: Install Docker Engine and Compose plugin
            ansible.builtin.apt:
                name:
                    - docker-ce
                    - docker-compose-plugin
                state: present
            notify: Ensure docker service is started and enabled

-   name: Set periodic Docker prune
    become: true
    ansible.builtin.cron:
        name: docker-prune
        job: 'docker system prune -af --filter until=72h'
        minute: '0'
        hour: '1'

-   name: Remove useless packages and dependencies
    become: true
    ansible.builtin.apt:
        autoclean: yes
        autoremove: yes
